# Generated by Django 4.1.4 on 2022-12-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAt', models.CharField(max_length=50)),
                ('intervenantAt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSl', models.CharField(max_length=50)),
                ('capaciteSl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUt', models.CharField(max_length=50)),
                ('effetifUt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Occupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activite')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.salle')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='activite',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.matiere'),
        ),
        migrations.AddField(
            model_name='activite',
            name='salle',
            field=models.ManyToManyField(null=True, through='app.Occupe', to='app.salle'),
        ),
        migrations.AddField(
            model_name='activite',
            name='utilisateur',
            field=models.ManyToManyField(null=True, through='app.Occupe', to='app.utilisateur'),
        ),
    ]
