# Generated by Django 4.1.4 on 2022-12-26 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matiere',
            old_name='nomAt',
            new_name='nomMt',
        ),
        migrations.AlterField(
            model_name='activite',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.matiere'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='effetifUt',
            field=models.IntegerField(null=True),
        ),
    ]
