# Generated by Django 4.1.4 on 2022-12-26 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_nomat_matiere_nommt_alter_activite_matiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupe',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.activite'),
        ),
        migrations.AlterField(
            model_name='occupe',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.salle'),
        ),
        migrations.AlterField(
            model_name='occupe',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur'),
        ),
    ]
