# Generated by Django 4.1.4 on 2023-02-05 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_occupe_activite_alter_occupe_salle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='effetifUt',
        ),
    ]
