# Generated by Django 4.1.4 on 2023-02-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_utilisateur_effetifut'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='effetifUt',
            field=models.IntegerField(null=True),
        ),
    ]
